# ==============================================================================
# Merged Lakeflow Source: citeline
# ==============================================================================
# This file is auto-generated by tools/scripts/merge_python_source.py
# Do not edit manually. Make changes to the source files instead.
# ==============================================================================

from abc import ABC, abstractmethod
from datetime import (
    date,
    datetime,
    timedelta,
    timezone,
)
from decimal import Decimal
from typing import Any, Iterator
import json
import time

from __future__ import annotations
from pyspark.sql import Row
from pyspark.sql.datasource import DataSource, DataSourceReader, SimpleDataSourceStreamReader
from urllib.parse import parse_qs, urlencode, urlparse
from pyspark.sql.types import *
import base64
import urllib.error
import urllib.request


def register_lakeflow_source(spark):
    """Register the Lakeflow Python source with Spark."""

    ########################################################
    # src/databricks/labs/community_connector/libs/utils.py
    ########################################################

    def _parse_struct(value: Any, field_type: StructType) -> Row:
        """Parse a dictionary into a PySpark Row based on StructType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for StructType, got {type(value)}")
        # Spark Python -> Arrow conversion require missing StructType fields to be assigned None.
        if value == {}:
            raise ValueError(
                "field in StructType cannot be an empty dict. "
                "Please assign None as the default value instead."
            )
        field_dict = {}
        for field in field_type.fields:
            if field.name in value:
                field_dict[field.name] = parse_value(value.get(field.name), field.dataType)
            elif field.nullable:
                field_dict[field.name] = None
            else:
                raise ValueError(f"Field {field.name} is not nullable but not found in the input")
        return Row(**field_dict)


    def _parse_array(value: Any, field_type: ArrayType) -> list:
        """Parse a list into a PySpark array based on ArrayType schema."""
        if not isinstance(value, list):
            if field_type.containsNull:
                return [parse_value(value, field_type.elementType)]
            raise ValueError(f"Expected a list for ArrayType, got {type(value)}")
        return [parse_value(v, field_type.elementType) for v in value]


    def _parse_map(value: Any, field_type: MapType) -> dict:
        """Parse a dictionary into a PySpark map based on MapType schema."""
        if not isinstance(value, dict):
            raise ValueError(f"Expected a dictionary for MapType, got {type(value)}")
        return {
            parse_value(k, field_type.keyType): parse_value(v, field_type.valueType)
            for k, v in value.items()
        }


    def _parse_string(value: Any) -> str:
        """Convert value to string."""
        return str(value)


    def _parse_integer(value: Any) -> int:
        """Convert value to integer."""
        if isinstance(value, str) and value.strip():
            return int(float(value)) if "." in value else int(value)
        if isinstance(value, (int, float)):
            return int(value)
        raise ValueError(f"Cannot convert {value} to integer")


    def _parse_float(value: Any) -> float:
        """Convert value to float."""
        return float(value)


    def _parse_decimal(value: Any) -> Decimal:
        """Convert value to Decimal."""
        return Decimal(value) if isinstance(value, str) and value.strip() else Decimal(str(value))


    def _parse_boolean(value: Any) -> bool:
        """Convert value to boolean."""
        if isinstance(value, str):
            lowered = value.lower()
            if lowered in ("true", "t", "yes", "y", "1"):
                return True
            if lowered in ("false", "f", "no", "n", "0"):
                return False
        return bool(value)


    def _parse_date(value: Any) -> datetime.date:
        """Convert value to date."""
        if isinstance(value, str):
            for fmt in ("%Y-%m-%d", "%m/%d/%Y", "%d-%m-%Y", "%Y/%m/%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
            return datetime.fromisoformat(value).date()
        if isinstance(value, datetime):
            return value.date()
        raise ValueError(f"Cannot convert {value} to date")


    def _parse_timestamp(value: Any) -> datetime:
        """Convert value to timestamp."""
        if isinstance(value, str):
            ts_value = value.replace("Z", "+00:00") if value.endswith("Z") else value
            try:
                return datetime.fromisoformat(ts_value)
            except ValueError:
                for fmt in ("%Y-%m-%d %H:%M:%S", "%Y/%m/%d %H:%M:%S"):
                    try:
                        return datetime.strptime(ts_value, fmt)
                    except ValueError:
                        continue
        elif isinstance(value, (int, float)):
            return datetime.fromtimestamp(value)
        elif isinstance(value, datetime):
            return value
        raise ValueError(f"Cannot convert {value} to timestamp")


    def _decode_string_to_bytes(value: str) -> bytes:
        """Try to decode a string as base64, then hex, then UTF-8."""
        try:
            return base64.b64decode(value)
        except Exception:
            pass
        try:
            return bytes.fromhex(value)
        except Exception:
            pass
        return value.encode("utf-8")


    def _parse_binary(value: Any) -> bytes:
        """Convert value to bytes. Tries base64, then hex, then UTF-8 for strings."""
        if isinstance(value, bytes):
            return value
        if isinstance(value, bytearray):
            return bytes(value)
        if isinstance(value, str):
            return _decode_string_to_bytes(value)
        if isinstance(value, list):
            return bytes(value)
        return str(value).encode("utf-8")


    # Mapping of primitive types to their parser functions
    _PRIMITIVE_PARSERS = {
        StringType: _parse_string,
        IntegerType: _parse_integer,
        LongType: _parse_integer,
        FloatType: _parse_float,
        DoubleType: _parse_float,
        DecimalType: _parse_decimal,
        BooleanType: _parse_boolean,
        DateType: _parse_date,
        TimestampType: _parse_timestamp,
        BinaryType: _parse_binary,
    }


    def parse_value(value: Any, field_type: DataType) -> Any:
        """
        Converts a JSON value into a PySpark-compatible data type based on the provided field type.
        """
        if value is None:
            return None

        # Handle complex types
        if isinstance(field_type, StructType):
            return _parse_struct(value, field_type)
        if isinstance(field_type, ArrayType):
            return _parse_array(value, field_type)
        if isinstance(field_type, MapType):
            return _parse_map(value, field_type)

        # Handle primitive types via type-based lookup
        try:
            field_type_class = type(field_type)
            if field_type_class in _PRIMITIVE_PARSERS:
                return _PRIMITIVE_PARSERS[field_type_class](value)

            # Check for custom UDT handling
            if hasattr(field_type, "fromJson"):
                return field_type.fromJson(value)

            raise TypeError(f"Unsupported field type: {field_type}")
        except (ValueError, TypeError) as e:
            raise ValueError(f"Error converting '{value}' ({type(value)}) to {field_type}: {str(e)}")


    ########################################################
    # src/databricks/labs/community_connector/interface/lakeflow_connect.py
    ########################################################

    class LakeflowConnect(ABC):
        """Base interface that each source connector must implement.

        Subclass this and implement all abstract methods to create a connector that
        integrates with the community connector library and ingestion pipeline.
        """

        def __init__(self, options: dict[str, str]) -> None:
            """
            Initialize the source connector with parameters needed to connect to the source.
            Args:
                options: A dictionary of parameters like authentication tokens, table names,
                    and other configurations.
            """
            self.options = options

        @abstractmethod
        def list_tables(self) -> list[str]:
            """
            List names of all the tables supported by the source connector.
            The list could either be a static list or retrieved from the source via API.
            Returns:
                A list of table names.
            """

        @abstractmethod
        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """
            Fetch the schema of a table.
            Args:
                table_name: The name of the table to fetch the schema for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the schema.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A StructType object representing the schema of the table.
            """

        @abstractmethod
        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """
            Fetch the metadata of a table.
            Args:
                table_name: The name of the table to fetch the metadata for.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to fetch the metadata.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A dictionary containing the metadata of the table. It should include the
                following keys:
                    - primary_keys: List of string names of the primary key columns of
                        the table.
                    - cursor_field: The name of the field to use as a cursor for
                        incremental loading.
                    - ingestion_type: The type of ingestion to use for the table. It
                        should be one of the following values:
                        - "snapshot": For snapshot loading.
                        - "cdc": Capture incremental changes (no delete support).
                        - "cdc_with_deletes": Capture incremental changes with delete
                            support. Requires implementing read_table_deletes().
                        - "append": Incremental append.
            """

        @abstractmethod
        def read_table(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read the records of a table and return an iterator of records and an offset.

            The framework calls this method repeatedly to paginate through data.
            start_offset is None only on the very first call of the very first run
            of a connector. On subsequent runs the framework resumes from the last
            checkpointed offset, so start_offset will already be populated. Each
            call returns (records, end_offset). The framework passes end_offset as
            start_offset to the next call. Pagination stops when the returned
            offset equals start_offset (i.e., no more data).

            For tables that cannot be incrementally read, return None as the offset to
            read the entire table in one batch. Non-checkpointable synthetic offsets can
            be used to split the data into multiple batches.

            Args:
                table_name: The name of the table to read.
                start_offset: The offset to start reading from. None only on the
                    first call of the first run; on subsequent runs it carries the
                    checkpointed offset from the previous run.
                table_options: A dictionary of options for accessing the table. For example,
                    the source API may require extra parameters needed to read the table.
                    If there are no additional options required, you can ignore this
                    parameter, and no options will be provided during execution.
                    Only add parameters to table_options if they are essential for accessing
                    or retrieving the data (such as specifying table namespaces).
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of records as JSON-compatible dicts. Do NOT convert
                    values according to get_table_schema(); the framework handles that.
                offset: A dict representing the position after this batch.
            """

        def read_table_deletes(
            self, table_name: str, start_offset: dict, table_options: dict[str, str]
        ) -> tuple[Iterator[dict], dict]:
            """
            Read deleted records from a table for CDC delete synchronization.
            This method is called when ingestion_type is "cdc_with_deletes" to fetch
            records that have been deleted from the source system.

            This method follows the same pagination and offset protocol as read_table:
            the framework calls it repeatedly, passing the previous end_offset as
            start_offset, until the returned offset equals start_offset.

            Override this method if any of your tables use ingestion_type
            "cdc_with_deletes". The default implementation raises NotImplementedError.

            The returned records should have at minimum the primary key fields and
            cursor field populated. Other fields can be null.

            Args:
                table_name: The name of the table to read deleted records from.
                start_offset: The offset to start reading from (same format as read_table).
                table_options: A dictionary of options for accessing the table.
            Returns:
                A two-element tuple of (records, offset).
                records: An iterator of deleted records (must include primary keys and cursor).
                offset: A dict (same format as read_table).
            """
            raise NotImplementedError(
                "read_table_deletes() must be implemented when ingestion_type is 'cdc_with_deletes'"
            )


    ########################################################
    # src/databricks/labs/community_connector/sources/citeline/citeline.py
    ########################################################

    _BASE_URL = "https://api.citeline.com"
    _TOKEN_URL = f"{_BASE_URL}/token"
    _MAX_RETRIES = 4
    _INITIAL_BACKOFF = 1.0
    _RETRIABLE_CODES = {429, 500, 502, 503, 504}
    _LOOKBACK_DAYS = 1
    _DEFAULT_PAGESIZE = 500
    _MAX_PAGESIZE = 2500
    # Default 'since' when no cursor is available (avoids HTTP 400 on /changes).
    _DEFAULT_SINCE = "2000-01-01"
    # Default 'since' when no cursor is available (avoids HTTP 400 on /changes).
    _DEFAULT_SINCE = "2000-01-01"


    # ---------------------------------------------------------------------------
    # Static table catalogue: connector table_name → API resource path
    # All resources sit under /v1/feed/{resource} and expose /changes.
    # ---------------------------------------------------------------------------
    _FEED_TABLES: dict[str, str] = {
        "trial": "trial",
        "trial_drugtargets": "trial/drugtargets",
        "drug": "drug",
        "drug_trends": "drug/trends",
        "drug_program": "drug/program",
        "drug_company": "drug/company",
        "drug_program_agg_company": "drug/program/aggregation/company",
        "drug_program_agg_country": "drug/program/aggregation/country",
        "drug_program_agg_disease": "drug/program/aggregation/disease",
        "drug_program_agg_region": "drug/program/aggregation/region",
        "investigator": "investigator",
        "organization": "organization",
        "organization_hierarchy": "organization/hierarchy",
        "organization_trials": "organization/trials",
        "hcp_profile": "hcp/profile",
        "physician_profile": "physician/profile",
        "drugevent": "drugevent",
        "drugevent_company": "drugevent/company",
        "drugevent_profile": "drugevent/profile",
        "drugcatalyst": "drugcatalyst",
        "drugcatalyst_company": "drugcatalyst/company",
        "drugcatalyst_timeseries": "drugcatalyst/timeseries",
        "deal": "deal",
        "device_product": "device/product",
        "device_trial": "device/trial",
        "device_event": "device/event",
        "device_catalyst": "device/catalyst",
        "device_catalyst_company": "device/catalyst/company",
        "device_company": "device/company",
        "patientproximity_investigator": "patientProximity/investigator",
        "patientproximity_organization": "patientProximity/organization",
        "patientproximity_physician": "patientProximity/Physician",
        "patientproximity_hcp": "patientProximity/hcp",
        "patientdiversity_investigator": "patientdiversity/investigator",
        "patientdiversity_organization": "patientdiversity/organization",
        "patientdiversity_physician": "patientdiversity/physician",
        "patientdiversity_hcp": "patientdiversity/hcp",
        "patientdiversity_global_organization": "patientdiversity/global/organization",
    }


    # Primary key fields per table, verified from live API data.
    # Fallback "id" is used for tables not yet accessible under the test account.
    _PRIMARY_KEYS: dict[str, list[str]] = {
        "trial": ["trialId"],
        "trial_drugtargets": ["trialId"],
        "investigator": ["investigatorId"],
        "organization": ["organizationId"],
        "organization_hierarchy": ["organizationId"],
        "organization_trials": ["organizationTrialId"],
    }
    _DEFAULT_PK = ["id"]

    # Maps table_name → the record field populated from ChangeItem.id in delete tombstones.
    _PK_FROM_CHANGE_ID: dict[str, str] = {
        "trial": "trialId",
        "trial_drugtargets": "trialId",
        "investigator": "investigatorId",
        "organization": "organizationId",
        "organization_hierarchy": "organizationId",
        "organization_trials": "organizationTrialId",
    }
    _DEFAULT_PK_CHANGE_FIELD = "id"


    # ---------------------------------------------------------------------------
    # JSON Schema → Spark type helpers
    # ---------------------------------------------------------------------------

    def _resolve_ref(ref: str, definitions: dict) -> dict:
        """Resolve a JSON Schema $ref like '#/definitions/Foo' to its definition."""
        if ref.startswith("#/definitions/"):
            name = ref[len("#/definitions/"):]
            return definitions.get(name, {})
        return {}


    def _json_schema_to_spark(field_schema: dict, definitions: dict, depth: int = 0):
        """Recursively convert a JSON Schema field definition to a Spark DataType.

        Objects and arrays are mapped to StringType; callers are expected to
        serialize those fields to JSON strings before returning records.
        """
        if depth > 6:
            return StringType()

        if "$ref" in field_schema:
            resolved = _resolve_ref(field_schema["$ref"], definitions)
            return _json_schema_to_spark(resolved, definitions, depth + 1)

        ftype = field_schema.get("type", "")

        # Handle nullable union like ["string", "null"]
        if isinstance(ftype, list):
            non_null = [t for t in ftype if t != "null"]
            ftype = non_null[0] if non_null else "string"

        if ftype == "integer":
            return LongType()
        if ftype == "number":
            return DoubleType()
        if ftype == "boolean":
            return BooleanType()
        if ftype in ("object", "array"):
            return StringType()  # serialised to JSON string
        if ftype == "string":
            return StringType()

        # anyOf / oneOf: take first non-null candidate
        for combiner in ("anyOf", "oneOf"):
            candidates = [
                s for s in field_schema.get(combiner, []) if s.get("type") != "null"
            ]
            if candidates:
                return _json_schema_to_spark(candidates[0], definitions, depth + 1)

        return StringType()


    def _parse_item_schema(raw_schema: dict) -> StructType:
        """Extract the item-level Spark StructType from a feed envelope JSON Schema.

        The API returns an envelope schema whose ``items`` array property references
        the actual record definition in ``definitions``.  This function navigates
        that reference and builds a flat StructType.
        """
        definitions = raw_schema.get("definitions", {})

        # Envelope: properties.items (array) → .items.$ref → record definition
        items_array = raw_schema.get("properties", {}).get("items", {})
        item_ref = items_array.get("items", {}).get("$ref", "")

        if item_ref:
            item_def = _resolve_ref(item_ref, definitions)
        else:
            # Fallback: treat the root schema as the item schema
            item_def = raw_schema

        properties = item_def.get("properties", {})
        if not properties:
            return StructType([StructField("data", StringType(), True)])

        return StructType([
            StructField(fname, _json_schema_to_spark(fschema, definitions), True)
            for fname, fschema in properties.items()
        ])


    # ---------------------------------------------------------------------------
    # Module-level helpers
    # ---------------------------------------------------------------------------

    def _extract_forward_token(next_page_url: str | None) -> str | None:
        """Extract the forwardToken query-string value from a nextPage URL."""
        if not next_page_url:
            return None
        try:
            qs = parse_qs(urlparse(next_page_url).query)
            tokens = qs.get("forwardToken", [])
            return tokens[0] if tokens else None
        except Exception:
            return None


    def _serialize_record(record: dict) -> dict:
        """Serialize dict/list field values to JSON strings for Spark StringType cols."""
        result = {}
        for k, v in record.items():
            if isinstance(v, (dict, list)):
                result[k] = json.dumps(v, separators=(",", ":"))
            else:
                result[k] = v
        return result


    def _apply_lookback(cursor: str) -> str:
        """Subtract _LOOKBACK_DAYS from a YYYY-MM-DD cursor string."""
        try:
            return (date.fromisoformat(cursor) - timedelta(days=_LOOKBACK_DAYS)).isoformat()
        except ValueError:
            return cursor


    # ---------------------------------------------------------------------------
    # Connector class
    # ---------------------------------------------------------------------------

    class CitelineLakeflowConnect(LakeflowConnect):
        """LakeflowConnect implementation for the Citeline (Informa) pharma data API."""

        def __init__(self, options: dict[str, str]) -> None:
            super().__init__(options)
            self._token = self._fetch_token(options["email"], options["password"])
            # Cap incremental reads at init time so a trigger never chases live writes.
            self._init_ts: str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            # Track which tables have already had the lookback subtraction applied
            # during this trigger instance (one connector instance per trigger).
            self._lookback_applied: set[str] = set()
            self._deletes_lookback_applied: set[str] = set()

        # ------------------------------------------------------------------
        # Authentication
        # ------------------------------------------------------------------

        def _fetch_token(self, email: str, password: str) -> str:
            """POST email+password to /token and return 'Bearer <jwt>'."""
            body = json.dumps({"email": email, "password": password}).encode()
            req = urllib.request.Request(
                _TOKEN_URL,
                data=body,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=20) as resp:
                data = json.loads(resp.read())
            return f"Bearer {data['access_token']}"

        # ------------------------------------------------------------------
        # HTTP
        # ------------------------------------------------------------------

        def _get(self, path: str, params: dict | None = None) -> dict:
            """Authenticated GET with exponential-backoff retry on transient errors.

            Raises urllib.error.HTTPError directly for client errors (4xx) — callers
            may catch 403/404 to handle subscription-gated endpoints gracefully.
            """
            url = f"{_BASE_URL}{path}"
            if params:
                url = f"{url}?{urlencode(params)}"

            backoff = _INITIAL_BACKOFF
            last_err: Exception | None = None
            for attempt in range(_MAX_RETRIES):
                req = urllib.request.Request(
                    url, headers={"Authorization": self._token}
                )
                try:
                    with urllib.request.urlopen(req, timeout=30) as resp:
                        return json.loads(resp.read())
                except urllib.error.HTTPError as exc:
                    last_err = exc
                    # 4xx are client errors — do not retry; let callers handle them.
                    if exc.code < 500 or attempt == _MAX_RETRIES - 1:
                        raise
                    retry_after = float(
                        exc.headers.get("Retry-After") or backoff
                    )
                    time.sleep(retry_after)
                    backoff = min(backoff * 2, 60.0)
                except urllib.error.URLError as exc:
                    last_err = exc
                    if attempt == _MAX_RETRIES - 1:
                        raise
                    time.sleep(backoff)
                    backoff = min(backoff * 2, 60.0)

            raise RuntimeError(
                f"All {_MAX_RETRIES} attempts failed for GET {path}: {last_err}"
            )

        # ------------------------------------------------------------------
        # Validation
        # ------------------------------------------------------------------

        def _validate_table(self, table_name: str) -> None:
            if table_name not in _FEED_TABLES:
                raise ValueError(
                    f"Table '{table_name}' is not supported. "
                    f"Supported tables: {sorted(_FEED_TABLES)}"
                )

        # ------------------------------------------------------------------
        # LakeflowConnect interface
        # ------------------------------------------------------------------

        def list_tables(self) -> list[str]:
            """Return the static list of all 39 Citeline feed resources."""
            return list(_FEED_TABLES.keys())

        def get_table_schema(
            self, table_name: str, table_options: dict[str, str]
        ) -> StructType:
            """Fetch the JSON Schema from /v1/feed/{resource}/schema and convert to StructType.

            The API returns an envelope schema; this method navigates into the
            items definition to produce the per-record Spark schema.  Object and
            array fields are mapped to StringType (JSON strings).

            Returns a minimal fallback schema (primary-key + updatedDate) when the
            endpoint returns 403 (not in subscription) or 404 (not found).
            """
            self._validate_table(table_name)
            resource = _FEED_TABLES[table_name]
            try:
                raw_schema = self._get(f"/v1/feed/{resource}/schema")
            except urllib.error.HTTPError as exc:
                if exc.code in (403, 404):
                    # Endpoint not accessible under this subscription — return a
                    # minimal schema so the framework can continue.
                    pk_fields = _PRIMARY_KEYS.get(table_name, _DEFAULT_PK)
                    fields = [StructField(pk, LongType(), True) for pk in pk_fields]
                    fields.append(StructField("updatedDate", StringType(), True))
                    return StructType(fields)
                raise

            schema = _parse_item_schema(raw_schema)

            # Ensure primary key field(s) and the CDC cursor field are present.
            pk_fields = _PRIMARY_KEYS.get(table_name, _DEFAULT_PK)
            existing = {f.name for f in schema.fields}
            extra: list[StructField] = []
            for pk in pk_fields:
                if pk not in existing:
                    extra.append(StructField(pk, LongType(), True))
            if "updatedDate" not in existing:
                extra.append(StructField("updatedDate", StringType(), True))

            return StructType(schema.fields + extra) if extra else schema

        def read_table_metadata(
            self, table_name: str, table_options: dict[str, str]
        ) -> dict:
            """Return static metadata. All Citeline feed resources are cdc_with_deletes."""
            self._validate_table(table_name)
            return {
                "primary_keys": _PRIMARY_KEYS.get(table_name, _DEFAULT_PK),
                "cursor_field": "updatedDate",
                "ingestion_type": "cdc_with_deletes",
            }

        def read_table(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read one microbatch of records.

            Routing logic:
              - start_offset is None OR phase=="feed" → paginate the full feed
                (/v1/feed/{resource}).  Once exhausted, transitions to the
                "changes" phase with cursor = _init_ts.
              - phase=="changes" → paginate /v1/feed/{resource}/changes, extracting
                "create" and "change" items.  "remove" items are skipped (handled
                by read_table_deletes).
              - cursor >= _init_ts → already caught up, returns empty + same offset.
            """
            self._validate_table(table_name)
            resource = _FEED_TABLES[table_name]
            max_records = int(table_options.get("max_records_per_batch", "200"))
            pagesize = min(max_records, _MAX_PAGESIZE)

            # ---- Full-feed phase ----
            if start_offset is None or start_offset.get("phase") == "feed":
                params: dict[str, str] = {"pagesize": str(pagesize)}
                fwd = (start_offset or {}).get("forward_token")
                if fwd:
                    params["forwardToken"] = fwd

                try:
                    body = self._get(f"/v1/feed/{resource}", params=params)
                except urllib.error.HTTPError as exc:
                    if exc.code in (403, 404):
                        # Endpoint not in subscription — return empty + stable offset.
                        return iter([]), {"phase": "changes", "cursor": self._init_ts}
                    raise

                records = [_serialize_record(item) for item in body.get("items", [])]

                next_token = _extract_forward_token(
                    body.get("pagination", {}).get("nextPage")
                )
                if next_token:
                    end_offset: dict = {"phase": "feed", "forward_token": next_token}
                else:
                    # Full feed exhausted — switch to incremental changes phase.
                    end_offset = {"phase": "changes", "cursor": self._init_ts}

                return iter(records), end_offset

            # ---- Changes phase ----
            cursor = start_offset.get("cursor")

            # Short-circuit: already at or past init time.
            if cursor and cursor >= self._init_ts:
                return iter([]), start_offset

            params = {"pagesize": str(pagesize)}
            fwd = start_offset.get("forward_token")
            if fwd:
                params["forwardToken"] = fwd
            else:
                # Always provide 'since' to avoid HTTP 400 on the changes endpoint.
                effective_since = cursor or _DEFAULT_SINCE
                if cursor and table_name not in self._lookback_applied:
                    effective_since = _apply_lookback(cursor)
                    self._lookback_applied.add(table_name)
                params["since"] = effective_since

            try:
                body = self._get(f"/v1/feed/{resource}/changes", params=params)
            except urllib.error.HTTPError as exc:
                if exc.code in (403, 404):
                    return iter([]), start_offset
                raise

            items = body.get("items", [])

            records = []
            max_date = cursor or ""
            for item in items:
                if item.get("type") == "remove":
                    continue  # deletes handled by read_table_deletes
                data = item.get("data")
                if data:
                    records.append(_serialize_record(data))
                d = item.get("date", "")
                if d > max_date:
                    max_date = d

            next_token = _extract_forward_token(
                body.get("pagination", {}).get("nextPage")
            )
            if next_token:
                end_offset = {
                    "phase": "changes",
                    "cursor": max_date or cursor,
                    "forward_token": next_token,
                }
            else:
                new_cursor = max_date if max_date else (cursor or self._init_ts)
                end_offset = {"phase": "changes", "cursor": new_cursor}

            # If nothing changed (cursor didn't advance, no records), signal done.
            if not records and end_offset == start_offset:
                return iter([]), start_offset

            return iter(records), end_offset

        def read_table_deletes(
            self,
            table_name: str,
            start_offset: dict,
            table_options: dict[str, str],
        ) -> tuple[Iterator[dict], dict]:
            """Read one microbatch of delete tombstones from /v1/feed/{resource}/changes?type=remove.

            Returns records containing only the primary key field and updatedDate
            (populated from ChangeItem.id and ChangeItem.date respectively).
            """
            self._validate_table(table_name)
            resource = _FEED_TABLES[table_name]
            max_records = int(table_options.get("max_records_per_batch", "200"))
            pagesize = min(max_records, _MAX_PAGESIZE)

            cursor = (start_offset or {}).get("cursor")
            if cursor and cursor >= self._init_ts:
                return iter([]), start_offset

            params: dict[str, str] = {"type": "remove", "pagesize": str(pagesize)}
            fwd = (start_offset or {}).get("forward_token")
            if fwd:
                params["forwardToken"] = fwd
            else:
                # Always provide 'since' to avoid HTTP 400 on the changes endpoint.
                effective_since = cursor or _DEFAULT_SINCE
                if cursor and table_name not in self._deletes_lookback_applied:
                    effective_since = _apply_lookback(cursor)
                    self._deletes_lookback_applied.add(table_name)
                params["since"] = effective_since

            try:
                body = self._get(f"/v1/feed/{resource}/changes", params=params)
            except urllib.error.HTTPError as exc:
                if exc.code in (403, 404):
                    return iter([]), start_offset or {"cursor": self._init_ts}
                raise
            items = body.get("items", [])

            pk_field = _PK_FROM_CHANGE_ID.get(table_name, _DEFAULT_PK_CHANGE_FIELD)
            records: list[dict] = []
            max_date = cursor or ""
            for item in items:
                change_id = item.get("id")
                date_str = item.get("date", "")
                records.append({pk_field: change_id, "updatedDate": date_str})
                if date_str > max_date:
                    max_date = date_str

            next_token = _extract_forward_token(
                body.get("pagination", {}).get("nextPage")
            )
            if next_token:
                end_offset: dict = {
                    "cursor": max_date or cursor,
                    "forward_token": next_token,
                }
            else:
                new_cursor = max_date if max_date else (cursor or self._init_ts)
                end_offset = {"cursor": new_cursor}

            # No records and cursor didn't advance — signal done.
            if not records and not next_token:
                stable_offset = start_offset or {"cursor": self._init_ts}
                if end_offset == stable_offset or start_offset is None:
                    return iter([]), end_offset

            if start_offset and end_offset == start_offset:
                return iter([]), start_offset

            return iter(records), end_offset


    ########################################################
    # src/databricks/labs/community_connector/sparkpds/lakeflow_datasource.py
    ########################################################

    LakeflowConnectImpl = CitelineLakeflowConnect
    # Constant option or column names
    METADATA_TABLE = "_lakeflow_metadata"
    TABLE_NAME = "tableName"
    TABLE_NAME_LIST = "tableNameList"
    TABLE_CONFIGS = "tableConfigs"
    IS_DELETE_FLOW = "isDeleteFlow"


    class LakeflowStreamReader(SimpleDataSourceStreamReader):
        """
        Implements a data source stream reader for Lakeflow Connect.
        Currently, only the simpleStreamReader is implemented, which uses a
        more generic protocol suitable for most data sources that support
        incremental loading.
        """

        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.lakeflow_connect = lakeflow_connect
            self.schema = schema

        def initialOffset(self):
            return {}

        def read(self, start: dict) -> (Iterator[tuple], dict):
            is_delete_flow = self.options.get(IS_DELETE_FLOW) == "true"
            # Strip delete flow options before passing to connector
            table_options = {
                k: v for k, v in self.options.items() if k != IS_DELETE_FLOW
            }

            if is_delete_flow:
                records, offset = self.lakeflow_connect.read_table_deletes(
                    self.options[TABLE_NAME], start, table_options
                )
            else:
                records, offset = self.lakeflow_connect.read_table(
                    self.options[TABLE_NAME], start, table_options
                )
            rows = map(lambda x: parse_value(x, self.schema), records)
            return rows, offset

        def readBetweenOffsets(self, start: dict, end: dict) -> Iterator[tuple]:
            # TODO: This does not ensure the records returned are identical across repeated calls.
            # For append-only tables, the data source must guarantee that reading from the same
            # start offset will always yield the same set of records.
            # For tables ingested as incremental CDC, it is only necessary that no new changes
            # are missed in the returned records.
            return self.read(start)[0]


    class LakeflowBatchReader(DataSourceReader):
        def __init__(
            self,
            options: dict[str, str],
            schema: StructType,
            lakeflow_connect: LakeflowConnect,
        ):
            self.options = options
            self.schema = schema
            self.lakeflow_connect = lakeflow_connect
            self.table_name = options[TABLE_NAME]

        def read(self, partition):
            all_records = []
            if self.table_name == METADATA_TABLE:
                all_records = self._read_table_metadata()
            else:
                all_records, _ = self.lakeflow_connect.read_table(
                    self.table_name, None, self.options
                )

            rows = map(lambda x: parse_value(x, self.schema), all_records)
            return iter(rows)

        def _read_table_metadata(self):
            table_name_list = self.options.get(TABLE_NAME_LIST, "")
            table_names = [o.strip() for o in table_name_list.split(",") if o.strip()]
            all_records = []
            table_configs = json.loads(self.options.get(TABLE_CONFIGS, "{}"))
            for table in table_names:
                metadata = self.lakeflow_connect.read_table_metadata(
                    table, table_configs.get(table, {})
                )
                all_records.append({TABLE_NAME: table, **metadata})
            return all_records


    class LakeflowSource(DataSource):
        """
        PySpark DataSource implementation for Lakeflow Connect.
        """

        def __init__(self, options):
            self.options = options
            # TEMPORARY: LakeflowConnectImpl is replaced with the actual implementation
            # class during merge. See the placeholder comment at the top of this file.
            self.lakeflow_connect = LakeflowConnectImpl(options)  # pylint: disable=abstract-class-instantiated

        @classmethod
        def name(cls):
            return "lakeflow_connect"

        def schema(self):
            table = self.options[TABLE_NAME]
            if table == METADATA_TABLE:
                return StructType(
                    [
                        StructField(TABLE_NAME, StringType(), False),
                        StructField("primary_keys", ArrayType(StringType()), True),
                        StructField("cursor_field", StringType(), True),
                        StructField("ingestion_type", StringType(), True),
                    ]
                )
            else:
                return self.lakeflow_connect.get_table_schema(table, self.options)

        def reader(self, schema: StructType):
            return LakeflowBatchReader(self.options, schema, self.lakeflow_connect)

        def simpleStreamReader(self, schema: StructType):
            return LakeflowStreamReader(self.options, schema, self.lakeflow_connect)


    spark.dataSource.register(LakeflowSource)
